In [1]:
import pandas as pd
import numpy as np

In [2]:


data = {
'Product_ID': ['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P009', 'P010',
'P011', 'P012', 'P013', 'P014', 'P015', 'P016', 'P002', 'P017'],
'Product_Name': ['Laptop', 'mouse', 'KEYBOARD', 'Monitor', None, 'usb cable', 'Headphones', 'Laptop',
'Webcam', 'microphone', 'Speaker', 'mouse', ' router ', 'Switch', 'Hub', 'Tablet', 'mouse', 'Printer'],
'Category': ['Electronics', 'electronics', 'ELECTRONICS', 'Computers', 'computers', 'Accessories',
'Accessories', 'Electronics', 'Electronics', 'Electronics', 'Audio', 'electronics',
'Networking', 'networking', 'Networking', 'Electronics', 'electronics', 'Office'],
'Supplier': ['Tech Corp', 'Tech Corp', 'Global Supply', 'Tech Corp', 'Global Supply', 'Accessory World',
'Accessory World', 'Tech Corp', 'Vision Tech', 'Vision Tech', 'Sound Inc', 'Tech Corp',
'Net Gear', 'Net Gear', 'Net Gear', 'Vision Tech', 'Tech Corp', 'Print Pro'],
'Quantity': [15, 50, -5, 30, None, 120, 45, 15, 'twenty', 60, 25, 50, 8, 14, None, 22, 50, 0],
'Unit_Price': [1200.00, 25.50, 45.00, 300.00, 50.00, 10.00, 80.00, 1200.00, 75.00, 99999.00,
None, 25.50, 120.00, 150.00, 45.00, 250.00, 25.50, -150.00],
'Reorder_Level': [5, 10, 10, 5, 10, 20, 15, 5, 10, 10, 5, 10, 5, 5, 5, 5, 10, 2],
'Last_Update': ['2025-01-10', '2025/01/12', '2025-01-15', '2025-01-18', None, '2025-01-20',
'2025-01-22', '2025-01-10', '2025-01-25', 'bad-date', '2025-02-01', '2025/01/12',
'2025-02-05', '2025-02-10', '2025-02-12', '2025-02-15', '2025/01/12', '2025-02-20']
}

In [3]:
#import to dataframe
df = pd.DataFrame(data)
#
df.head()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Tech Corp,15,1200.0,5,2025-01-10
1,P002,mouse,electronics,Tech Corp,50,25.5,10,2025/01/12
2,P003,KEYBOARD,ELECTRONICS,Global Supply,-5,45.0,10,2025-01-15
3,P004,Monitor,Computers,Tech Corp,30,300.0,5,2025-01-18
4,P005,None,computers,Global Supply,None,50.0,10,None

In [4]:
df.tail()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
13,P014,Switch,networking,Net Gear,14,150.0,5,2025-02-10
14,P015,Hub,Networking,Net Gear,None,45.0,5,2025-02-12
15,P016,Tablet,Electronics,Vision Tech,22,250.0,5,2025-02-15
16,P002,mouse,electronics,Tech Corp,50,25.5,10,2025/01/12
17,P017,Printer,Office,Print Pro,0,-150.0,2,2025-02-20

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     18 non-null     object
 1   Product_Name   17 non-null     object
 2   Category       18 non-null     object
 3   Supplier       18 non-null     object
 4   Quantity       16 non-null     object
 5   Unit_Price     17 non-null     float64
 6   Reorder_Level  18 non-null     int64
 7   Last_Update    17 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 1.2+ KB

In [6]:
df.describe()

         Unit_Price  Reorder_Level
count     17.000000      18.000000
mean    6085.323529       8.166667
std    24204.057982       4.395854
min     -150.000000       2.000000
25%       25.500000       5.000000
50%       75.000000       7.500000
75%      250.000000      10.000000
max    99999.000000      20.000000

In [7]:
df.isnull().sum()

Product_ID       0
Product_Name     1
Category         0
Supplier         0
Quantity         2
Unit_Price       1
Reorder_Level    0
Last_Update      1
dtype: int64

In [8]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Tech Corp,15,1200.0,5,2025-01-10
1,P002,mouse,electronics,Tech Corp,50,25.5,10,2025/01/12
2,P003,KEYBOARD,ELECTRONICS,Global Supply,-5,45.0,10,2025-01-15
3,P004,Monitor,Computers,Tech Corp,30,300.0,5,2025-01-18
4,P005,None,computers,Global Supply,None,50.0,10,None
5,P006,usb cable,Accessories,Accessory World,120,10.0,20,2025-01-20
6,P007,Headphones,Accessories,Accessory World,45,80.0,15,2025-01-22
7,P008,Laptop,Electronics,Tech Corp,15,1200.0,5,2025-01-10
8,P009,Webcam,Electronics,Vision Tech,twenty,75.0,10,2025-01-25
9,P010,microphone,Electronics,Vision Tech,60,99999.0,10,bad-date
10,P011,Speaker,Audio,Sound Inc,25,NaN,5,2025-02-01
11,P012,mouse,electronics,Tech Corp,50,25.5,10,2025/01/12
12,P013,router,Networking,Net Gear,8,120.0,5,2025-02-05
13,P014,Switch,networking,Net Gear,14,150.0,5,2025-02-10
14,P015,Hub,Networking,Net Gear,None,45.0,5,2025-02-12
15,P016,Tablet,Electronics,Vision Tech,22,250.0,5,2025-02-15
16,P002,mouse,electronics,Tech Corp,50,25.5,10,2025/01/12
17,P017,Printer,Office,Print Pro,0,-150.0,2,2025-02-20

In [9]:
#removing duplicate row
df = df.drop(index=16)

In [10]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Tech Corp,15,1200.0,5,2025-01-10
1,P002,mouse,electronics,Tech Corp,50,25.5,10,2025/01/12
2,P003,KEYBOARD,ELECTRONICS,Global Supply,-5,45.0,10,2025-01-15
3,P004,Monitor,Computers,Tech Corp,30,300.0,5,2025-01-18
4,P005,None,computers,Global Supply,None,50.0,10,None
5,P006,usb cable,Accessories,Accessory World,120,10.0,20,2025-01-20
6,P007,Headphones,Accessories,Accessory World,45,80.0,15,2025-01-22
7,P008,Laptop,Electronics,Tech Corp,15,1200.0,5,2025-01-10
8,P009,Webcam,Electronics,Vision Tech,twenty,75.0,10,2025-01-25
9,P010,microphone,Electronics,Vision Tech,60,99999.0,10,bad-date
10,P011,Speaker,Audio,Sound Inc,25,NaN,5,2025-02-01
11,P012,mouse,electronics,Tech Corp,50,25.5,10,2025/01/12
12,P013,router,Networking,Net Gear,8,120.0,5,2025-02-05
13,P014,Switch,networking,Net Gear,14,150.0,5,2025-02-10
14,P015,Hub,Networking,Net Gear,None,45.0,5,2025-02-12
15,P016,Tablet,Electronics,Vision Tech,22,250.0,5,2025-02-15
17,P017,Printer,Office,Print Pro,0,-150.0,2,2025-02-20

In [11]:
df = df.drop(index=4)

In [12]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Tech Corp,15,1200.0,5,2025-01-10
1,P002,mouse,electronics,Tech Corp,50,25.5,10,2025/01/12
2,P003,KEYBOARD,ELECTRONICS,Global Supply,-5,45.0,10,2025-01-15
3,P004,Monitor,Computers,Tech Corp,30,300.0,5,2025-01-18
5,P006,usb cable,Accessories,Accessory World,120,10.0,20,2025-01-20
6,P007,Headphones,Accessories,Accessory World,45,80.0,15,2025-01-22
7,P008,Laptop,Electronics,Tech Corp,15,1200.0,5,2025-01-10
8,P009,Webcam,Electronics,Vision Tech,twenty,75.0,10,2025-01-25
9,P010,microphone,Electronics,Vision Tech,60,99999.0,10,bad-date
10,P011,Speaker,Audio,Sound Inc,25,NaN,5,2025-02-01
11,P012,mouse,electronics,Tech Corp,50,25.5,10,2025/01/12
12,P013,router,Networking,Net Gear,8,120.0,5,2025-02-05
13,P014,Switch,networking,Net Gear,14,150.0,5,2025-02-10
14,P015,Hub,Networking,Net Gear,None,45.0,5,2025-02-12
15,P016,Tablet,Electronics,Vision Tech,22,250.0,5,2025-02-15
17,P017,Printer,Office,Print Pro,0,-150.0,2,2025-02-20

In [13]:
df["Product_Name"] = (
    df["Product_Name"]
    .str.strip()
    .str.title()
    .replace("None", np.nan)
    .tolist()
)

df["Product_Name"]

0         Laptop
1          Mouse
2       Keyboard
3        Monitor
5      Usb Cable
6     Headphones
7         Laptop
8         Webcam
9     Microphone
10       Speaker
11         Mouse
12        Router
13        Switch
14           Hub
15        Tablet
17       Printer
Name: Product_Name, dtype: object

In [14]:
df["Category"] = (
    df["Category"]
    .str.strip()
    .str.title()
    .tolist()
)

df["Category"]

0     Electronics
1     Electronics
2     Electronics
3       Computers
5     Accessories
6     Accessories
7     Electronics
8     Electronics
9     Electronics
10          Audio
11    Electronics
12     Networking
13     Networking
14     Networking
15    Electronics
17         Office
Name: Category, dtype: object

In [15]:
df["Supplier"] = (
    df["Supplier"]
    .str.strip()
    .str.title()
    .tolist()
)

df["Supplier"]

0           Tech Corp
1           Tech Corp
2       Global Supply
3           Tech Corp
5     Accessory World
6     Accessory World
7           Tech Corp
8         Vision Tech
9         Vision Tech
10          Sound Inc
11          Tech Corp
12           Net Gear
13           Net Gear
14           Net Gear
15        Vision Tech
17          Print Pro
Name: Supplier, dtype: object

In [16]:
def change(value):
    if value == "twenty":
        return 20
    elif isinstance(value, (int, float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else:
        return np.nan
df["Quantity"] = df["Quantity"].apply(change)

df["Quantity"]

0      15.0
1      50.0
2      -5.0
3      30.0
5     120.0
6      45.0
7      15.0
8      20.0
9      60.0
10     25.0
11     50.0
12      8.0
13     14.0
14      NaN
15     22.0
17      0.0
Name: Quantity, dtype: float64

In [17]:
df["Quantity"] = (
    df["Quantity"]
    .astype(str)
    .replace("None", np.nan)
    .astype(float)
)
df["Quantity"]

0      15.0
1      50.0
2      -5.0
3      30.0
5     120.0
6      45.0
7      15.0
8      20.0
9      60.0
10     25.0
11     50.0
12      8.0
13     14.0
14      NaN
15     22.0
17      0.0
Name: Quantity, dtype: float64

In [18]:
df["Reorder_Level"] = (
    df["Reorder_Level"]
    .astype(int)
    .astype(float)
)
df["Reorder_Level"]

0      5.0
1     10.0
2     10.0
3      5.0
5     20.0
6     15.0
7      5.0
8     10.0
9     10.0
10     5.0
11    10.0
12     5.0
13     5.0
14     5.0
15     5.0
17     2.0
Name: Reorder_Level, dtype: float64

In [19]:
df["Unit_Price"] = (
    df["Unit_Price"]
    .astype(str)
    .replace("None", np.nan)
    .astype(float)
)
df["Unit_Price"]

0      1200.0
1        25.5
2        45.0
3       300.0
5        10.0
6        80.0
7      1200.0
8        75.0
9     99999.0
10        NaN
11       25.5
12      120.0
13      150.0
14       45.0
15      250.0
17     -150.0
Name: Unit_Price, dtype: float64

In [20]:
from dateutil import parser

def clean_date(date_str):
    try:
        return parser.parse(date_str, dayfirst=True)
    except Exception:
        return pd.NaT
df["Last_Update"] = df["Last_Update"].apply(clean_date)
df["Last_Update"]

0    2025-10-01
1    2025-12-01
2    2025-01-15
3    2025-01-18
5    2025-01-20
6    2025-01-22
7    2025-10-01
8    2025-01-25
9           NaT
10   2025-01-02
11   2025-12-01
12   2025-05-02
13   2025-10-02
14   2025-12-02
15   2025-02-15
17   2025-02-20
Name: Last_Update, dtype: datetime64[ns]

In [21]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Tech Corp,15.0,1200.0,5.0,2025-10-01
1,P002,Mouse,Electronics,Tech Corp,50.0,25.5,10.0,2025-12-01
2,P003,Keyboard,Electronics,Global Supply,-5.0,45.0,10.0,2025-01-15
3,P004,Monitor,Computers,Tech Corp,30.0,300.0,5.0,2025-01-18
5,P006,Usb Cable,Accessories,Accessory World,120.0,10.0,20.0,2025-01-20
6,P007,Headphones,Accessories,Accessory World,45.0,80.0,15.0,2025-01-22
7,P008,Laptop,Electronics,Tech Corp,15.0,1200.0,5.0,2025-10-01
8,P009,Webcam,Electronics,Vision Tech,20.0,75.0,10.0,2025-01-25
9,P010,Microphone,Electronics,Vision Tech,60.0,99999.0,10.0,NaT
10,P011,Speaker,Audio,Sound Inc,25.0,NaN,5.0,2025-01-02
11,P012,Mouse,Electronics,Tech Corp,50.0,25.5,10.0,2025-12-01
12,P013,Router,Networking,Net Gear,8.0,120.0,5.0,2025-05-02
13,P014,Switch,Networking,Net Gear,14.0,150.0,5.0,2025-10-02
14,P015,Hub,Networking,Net Gear,NaN,45.0,5.0,2025-12-02
15,P016,Tablet,Electronics,Vision Tech,22.0,250.0,5.0,2025-02-15
17,P017,Printer,Office,Print Pro,0.0,-150.0,2.0,2025-02-20

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 17
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     16 non-null     object
 1   Product_Name   16 non-null     object
 2   Category       16 non-null     object
 3   Supplier       16 non-null     object
 4   Quantity       15 non-null     float64
 5   Unit_Price     15 non-null     float64
 6   Reorder_Level  16 non-null     float64
 7   Last_Update    15 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 1.1+ KB

In [23]:
#unrealistic record
df =  df.drop(index=2)
df =  df.drop(index=17)

In [24]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Tech Corp,15.0,1200.0,5.0,2025-10-01
1,P002,Mouse,Electronics,Tech Corp,50.0,25.5,10.0,2025-12-01
3,P004,Monitor,Computers,Tech Corp,30.0,300.0,5.0,2025-01-18
5,P006,Usb Cable,Accessories,Accessory World,120.0,10.0,20.0,2025-01-20
6,P007,Headphones,Accessories,Accessory World,45.0,80.0,15.0,2025-01-22
7,P008,Laptop,Electronics,Tech Corp,15.0,1200.0,5.0,2025-10-01
8,P009,Webcam,Electronics,Vision Tech,20.0,75.0,10.0,2025-01-25
9,P010,Microphone,Electronics,Vision Tech,60.0,99999.0,10.0,NaT
10,P011,Speaker,Audio,Sound Inc,25.0,NaN,5.0,2025-01-02
11,P012,Mouse,Electronics,Tech Corp,50.0,25.5,10.0,2025-12-01
12,P013,Router,Networking,Net Gear,8.0,120.0,5.0,2025-05-02
13,P014,Switch,Networking,Net Gear,14.0,150.0,5.0,2025-10-02
14,P015,Hub,Networking,Net Gear,NaN,45.0,5.0,2025-12-02
15,P016,Tablet,Electronics,Vision Tech,22.0,250.0,5.0,2025-02-15

In [25]:
restock = df["Quantity"] < df["Reorder_Level"]
print(restock)

0     False
1     False
3     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [26]:
Avg_Price = df.groupby("Category")["Unit_Price"].mean()
print(Avg_Price)

Category
Accessories       45.000000
Audio                   NaN
Computers        300.000000
Electronics    14682.142857
Networking       105.000000
Name: Unit_Price, dtype: float64

In [27]:
top_supplier = df["Supplier"].value_counts()
print(top_supplier)

Supplier
Tech Corp          5
Vision Tech        3
Net Gear           3
Accessory World    2
Sound Inc          1
Name: count, dtype: int64

In [28]:
Expensive_Product = df.nlargest(5, "Unit_Price")
print(Expensive_Product [["Product_ID", "Product_Name", "Unit_Price"]])

   Product_ID Product_Name  Unit_Price
9        P010   Microphone     99999.0
0        P001       Laptop      1200.0
7        P008       Laptop      1200.0
3        P004      Monitor       300.0
15       P016       Tablet       250.0

In [29]:
df.sort_values(["Category", "Unit_Price"], ascending=[True, False])

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
6,P007,Headphones,Accessories,Accessory World,45.0,80.0,15.0,2025-01-22
5,P006,Usb Cable,Accessories,Accessory World,120.0,10.0,20.0,2025-01-20
10,P011,Speaker,Audio,Sound Inc,25.0,NaN,5.0,2025-01-02
3,P004,Monitor,Computers,Tech Corp,30.0,300.0,5.0,2025-01-18
9,P010,Microphone,Electronics,Vision Tech,60.0,99999.0,10.0,NaT
0,P001,Laptop,Electronics,Tech Corp,15.0,1200.0,5.0,2025-10-01
7,P008,Laptop,Electronics,Tech Corp,15.0,1200.0,5.0,2025-10-01
15,P016,Tablet,Electronics,Vision Tech,22.0,250.0,5.0,2025-02-15
8,P009,Webcam,Electronics,Vision Tech,20.0,75.0,10.0,2025-01-25
1,P002,Mouse,Electronics,Tech Corp,50.0,25.5,10.0,2025-12-01
11,P012,Mouse,Electronics,Tech Corp,50.0,25.5,10.0,2025-12-01
13,P014,Switch,Networking,Net Gear,14.0,150.0,5.0,2025-10-02
12,P013,Router,Networking,Net Gear,8.0,120.0,5.0,2025-05-02
14,P015,Hub,Networking,Net Gear,NaN,45.0,5.0,2025-12-02