In [257]:
import pandas as pd
import numpy as np

In [258]:
data = {
    "Product_ID": ["P001", "P002", "P003", "P004", "P005", "P006", "P007", "P008", "P009", "P010", "P011", "P012", "P013", "P014", "P015", "P016", "P017", "P017", "P018", "P019"],

    "Product_Name": ["Laptop", "laptop", "LAPTOP", "Mouse", "mouse", "Keyboard", "", "Monitor", "Printer", "printer", "USB Cable", "USB CABLE", "Tablet", "Headphones", "headphones", "Webcam", "webcam", "webcam", "Desk", "chair"],

    "Category": ["Electronics", "electronics", "ELECTRONICS", "Accessories", "accessories", "Accessories", "Electronics", "electronics", "Office Supplies", "Office Supplies", "Accessories", "ACCESSORIES", "Electronics", "Electronics", "electronics", "Electronics", "Electronics", "Electronics", "Office Supplies", "office supplies"],

    "Supplier": ["TechWorld", "Tech World", "TechWorld", "CompuStore", "Compu Store", "CompuStore", "TechWorld", "TechWorld", "OfficeHub", "Office Hub", "CompuStore", "CompuStore", "TechWorld", "TechWorld", "Tech World", "TechWorld", "TechWorld", "TechWorld", "OfficeHub", "Office Hub"],

    "Quantity": [25, 20, 21, 50, -5, 35, 15, 10, 8, 12, 100, None, 5, 30, 25, 17, 18, 18, -10, "thirty"],

    "Unit_Price": [850, 900, 850, 25, 20, 45, 700, 1500, -300, 250, 10, 10, 999999, 75, 80, 60, 60, 60, 120, 150],

    "Reorder_Level": [10, 10, 10, 15, 10, 10, 5, 5, 3, 5, 20, 20, 3, 10, 10, 5, 5, 5, 5, 10],

    "Last_Update": ["2025-01-10", "2025/01/12", "01-15-2025", "2025-02-01","2025-02-03", "2025-02-05", "2025-02-10", None,"2025-03-01", "2025/03/05", "2025-03-10", "2025-03-12","2025-03-15", "invalid-date", "2025-04-01", "2025-04-05","2025-04-05", "2025-04-05", "2025-04-10", "2025-04-15"]}

In [259]:
df = pd.DataFrame(data)

df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechWorld,25,850,10,2025-01-10
1,P002,laptop,electronics,Tech World,20,900,10,2025/01/12
2,P003,LAPTOP,ELECTRONICS,TechWorld,21,850,10,01-15-2025
3,P004,Mouse,Accessories,CompuStore,50,25,15,2025-02-01
4,P005,mouse,accessories,Compu Store,-5,20,10,2025-02-03
5,P006,Keyboard,Accessories,CompuStore,35,45,10,2025-02-05
6,P007,,Electronics,TechWorld,15,700,5,2025-02-10
7,P008,Monitor,electronics,TechWorld,10,1500,5,NaN
8,P009,Printer,Office Supplies,OfficeHub,8,-300,3,2025-03-01
9,P010,printer,Office Supplies,Office Hub,12,250,5,2025/03/05
10,P011,USB Cable,Accessories,CompuStore,100,10,20,2025-03-10
11,P012,USB CABLE,ACCESSORIES,CompuStore,None,10,20,2025-03-12
12,P013,Tablet,Electronics,TechWorld,5,999999,3,2025-03-15
13,P014,Headphones,Electronics,TechWorld,30,75,10,invalid-date
14,P015,headphones,electronics,Tech World,25,80,10,2025-04-01
15,P016,Webcam,Electronics,TechWorld,17,60,5,2025-04-05
16,P017,webcam,Electronics,TechWorld,18,60,5,2025-04-05
17,P017,webcam,Electronics,TechWorld,18,60,5,2025-04-05
18,P018,Desk,Office Supplies,OfficeHub,-10,120,5,2025-04-10
19,P019,chair,office supplies,Office Hub,thirty,150,10,2025-04-15

In [260]:
df.head()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechWorld,25,850,10,2025-01-10
1,P002,laptop,electronics,Tech World,20,900,10,2025/01/12
2,P003,LAPTOP,ELECTRONICS,TechWorld,21,850,10,01-15-2025
3,P004,Mouse,Accessories,CompuStore,50,25,15,2025-02-01
4,P005,mouse,accessories,Compu Store,-5,20,10,2025-02-03

In [261]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     20 non-null     str
 1   Product_Name   20 non-null     str
 2   Category       20 non-null     str
 3   Supplier       20 non-null     str
 4   Quantity       19 non-null     object
 5   Unit_Price     20 non-null     int64
 6   Reorder_Level  20 non-null     int64
 7   Last_Update    19 non-null     str
dtypes: int64(2), object(1), str(5)
memory usage: 1.4+ KB

In [262]:
df.describe()

          Unit_Price  Reorder_Level
count      20.000000       20.00000
mean    50273.200000        8.80000
std    223542.686105        4.96938
min      -300.000000        3.00000
25%        40.000000        5.00000
50%        77.500000       10.00000
75%       737.500000       10.00000
max    999999.000000       20.00000

In [263]:
#cleaning the data
df.dropna()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechWorld,25,850,10,2025-01-10
1,P002,laptop,electronics,Tech World,20,900,10,2025/01/12
2,P003,LAPTOP,ELECTRONICS,TechWorld,21,850,10,01-15-2025
3,P004,Mouse,Accessories,CompuStore,50,25,15,2025-02-01
4,P005,mouse,accessories,Compu Store,-5,20,10,2025-02-03
5,P006,Keyboard,Accessories,CompuStore,35,45,10,2025-02-05
6,P007,,Electronics,TechWorld,15,700,5,2025-02-10
8,P009,Printer,Office Supplies,OfficeHub,8,-300,3,2025-03-01
9,P010,printer,Office Supplies,Office Hub,12,250,5,2025/03/05
10,P011,USB Cable,Accessories,CompuStore,100,10,20,2025-03-10
12,P013,Tablet,Electronics,TechWorld,5,999999,3,2025-03-15
13,P014,Headphones,Electronics,TechWorld,30,75,10,invalid-date
14,P015,headphones,electronics,Tech World,25,80,10,2025-04-01
15,P016,Webcam,Electronics,TechWorld,17,60,5,2025-04-05
16,P017,webcam,Electronics,TechWorld,18,60,5,2025-04-05
17,P017,webcam,Electronics,TechWorld,18,60,5,2025-04-05
18,P018,Desk,Office Supplies,OfficeHub,-10,120,5,2025-04-10
19,P019,chair,office supplies,Office Hub,thirty,150,10,2025-04-15

In [264]:
df.rename(columns={
    "Product_ID": "Product Id",
    "Product_Name": "Product Name",
    "Unit_Price": "Unit Price",
    "Recorder_Level": "Recorder Level",
    "Last_Update": "Last Update"
})

,Product Id,Product Name,Category,Supplier,Quantity,Unit Price,Reorder_Level,Last Update
0,P001,Laptop,Electronics,TechWorld,25,850,10,2025-01-10
1,P002,laptop,electronics,Tech World,20,900,10,2025/01/12
2,P003,LAPTOP,ELECTRONICS,TechWorld,21,850,10,01-15-2025
3,P004,Mouse,Accessories,CompuStore,50,25,15,2025-02-01
4,P005,mouse,accessories,Compu Store,-5,20,10,2025-02-03
5,P006,Keyboard,Accessories,CompuStore,35,45,10,2025-02-05
6,P007,,Electronics,TechWorld,15,700,5,2025-02-10
7,P008,Monitor,electronics,TechWorld,10,1500,5,NaN
8,P009,Printer,Office Supplies,OfficeHub,8,-300,3,2025-03-01
9,P010,printer,Office Supplies,Office Hub,12,250,5,2025/03/05
10,P011,USB Cable,Accessories,CompuStore,100,10,20,2025-03-10
11,P012,USB CABLE,ACCESSORIES,CompuStore,None,10,20,2025-03-12
12,P013,Tablet,Electronics,TechWorld,5,999999,3,2025-03-15
13,P014,Headphones,Electronics,TechWorld,30,75,10,invalid-date
14,P015,headphones,electronics,Tech World,25,80,10,2025-04-01
15,P016,Webcam,Electronics,TechWorld,17,60,5,2025-04-05
16,P017,webcam,Electronics,TechWorld,18,60,5,2025-04-05
17,P017,webcam,Electronics,TechWorld,18,60,5,2025-04-05
18,P018,Desk,Office Supplies,OfficeHub,-10,120,5,2025-04-10
19,P019,chair,office supplies,Office Hub,thirty,150,10,2025-04-15

In [265]:
df["Product_Name"] = (
    df["Product_Name"]
    .str.strip()
    .str.title()
    .str.replace(r"[\s-]+", " ", regex=True)
    .tolist()
)

df["Product_Name"].to_list()

['Laptop',
 'Laptop',
 'Laptop',
 'Mouse',
 'Mouse',
 'Keyboard',
 '',
 'Monitor',
 'Printer',
 'Printer',
 'Usb Cable',
 'Usb Cable',
 'Tablet',
 'Headphones',
 'Headphones',
 'Webcam',
 'Webcam',
 'Webcam',
 'Desk',
 'Chair']

In [266]:
df["Category"] = (
     df["Category"]
    .str.strip()
    .str.title()
    .str.replace(r"[\s-]+", " ", regex=True)
    .tolist()
)

df["Category"].to_list()

['Electronics',
 'Electronics',
 'Electronics',
 'Accessories',
 'Accessories',
 'Accessories',
 'Electronics',
 'Electronics',
 'Office Supplies',
 'Office Supplies',
 'Accessories',
 'Accessories',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Office Supplies',
 'Office Supplies']

In [267]:
df.replace({
    "Compu Store": "Computer Store",
    "Techworld": "Tech World",
    "CompuStore": "Computer Store",
    "Officehub": "Office Hub",
    "Compustore": "Computer Store"
})

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechWorld,25,850,10,2025-01-10
1,P002,Laptop,Electronics,Tech World,20,900,10,2025/01/12
2,P003,Laptop,Electronics,TechWorld,21,850,10,01-15-2025
3,P004,Mouse,Accessories,Computer Store,50,25,15,2025-02-01
4,P005,Mouse,Accessories,Computer Store,-5,20,10,2025-02-03
5,P006,Keyboard,Accessories,Computer Store,35,45,10,2025-02-05
6,P007,,Electronics,TechWorld,15,700,5,2025-02-10
7,P008,Monitor,Electronics,TechWorld,10,1500,5,NaN
8,P009,Printer,Office Supplies,OfficeHub,8,-300,3,2025-03-01
9,P010,Printer,Office Supplies,Office Hub,12,250,5,2025/03/05
10,P011,Usb Cable,Accessories,Computer Store,100,10,20,2025-03-10
11,P012,Usb Cable,Accessories,Computer Store,None,10,20,2025-03-12
12,P013,Tablet,Electronics,TechWorld,5,999999,3,2025-03-15
13,P014,Headphones,Electronics,TechWorld,30,75,10,invalid-date
14,P015,Headphones,Electronics,Tech World,25,80,10,2025-04-01
15,P016,Webcam,Electronics,TechWorld,17,60,5,2025-04-05
16,P017,Webcam,Electronics,TechWorld,18,60,5,2025-04-05
17,P017,Webcam,Electronics,TechWorld,18,60,5,2025-04-05
18,P018,Desk,Office Supplies,OfficeHub,-10,120,5,2025-04-10
19,P019,Chair,Office Supplies,Office Hub,thirty,150,10,2025-04-15

In [268]:
def clean_quantity(value):
    if value == "thirty":
        return 30
    elif isinstance(value, (int, float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else:
        return np.nan
df["Quantity"] = df["Quantity"].apply(clean_quantity)

df["Quantity"]

0      25.0
1      20.0
2      21.0
3      50.0
4      -5.0
5      35.0
6      15.0
7      10.0
8       8.0
9      12.0
10    100.0
11      NaN
12      5.0
13     30.0
14     25.0
15     17.0
16     18.0
17     18.0
18    -10.0
19     30.0
Name: Quantity, dtype: float64

In [269]:
df["Unit_Price"] = (
    df["Unit_Price"]
    .astype(str)
    .replace('[-,]', "", regex=True)
    .replace("NaN", np.nan)
    .astype(float)
)

df["Unit_Price"]

0        850.0
1        900.0
2        850.0
3         25.0
4         20.0
5         45.0
6        700.0
7       1500.0
8        300.0
9        250.0
10        10.0
11        10.0
12    999999.0
13        75.0
14        80.0
15        60.0
16        60.0
17        60.0
18       120.0
19       150.0
Name: Unit_Price, dtype: float64

In [270]:
df.drop_duplicates()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechWorld,25.0,850.0,10,2025-01-10
1,P002,Laptop,Electronics,Tech World,20.0,900.0,10,2025/01/12
2,P003,Laptop,Electronics,TechWorld,21.0,850.0,10,01-15-2025
3,P004,Mouse,Accessories,CompuStore,50.0,25.0,15,2025-02-01
4,P005,Mouse,Accessories,Compu Store,-5.0,20.0,10,2025-02-03
5,P006,Keyboard,Accessories,CompuStore,35.0,45.0,10,2025-02-05
6,P007,,Electronics,TechWorld,15.0,700.0,5,2025-02-10
7,P008,Monitor,Electronics,TechWorld,10.0,1500.0,5,NaN
8,P009,Printer,Office Supplies,OfficeHub,8.0,300.0,3,2025-03-01
9,P010,Printer,Office Supplies,Office Hub,12.0,250.0,5,2025/03/05
10,P011,Usb Cable,Accessories,CompuStore,100.0,10.0,20,2025-03-10
11,P012,Usb Cable,Accessories,CompuStore,NaN,10.0,20,2025-03-12
12,P013,Tablet,Electronics,TechWorld,5.0,999999.0,3,2025-03-15
13,P014,Headphones,Electronics,TechWorld,30.0,75.0,10,invalid-date
14,P015,Headphones,Electronics,Tech World,25.0,80.0,10,2025-04-01
15,P016,Webcam,Electronics,TechWorld,17.0,60.0,5,2025-04-05
16,P017,Webcam,Electronics,TechWorld,18.0,60.0,5,2025-04-05
18,P018,Desk,Office Supplies,OfficeHub,-10.0,120.0,5,2025-04-10
19,P019,Chair,Office Supplies,Office Hub,30.0,150.0,10,2025-04-15

In [271]:
from dateutil import parser

def clean_date(date_str):
    try:
        return parser.parse(date_str, dayfirst=True)
    except Exception:
        return pd.NaT

df["Last_Update"] = df["Last_Update"].apply(clean_date)
df["Last_Update"]

0    2025-10-01
1    2025-12-01
2    2025-01-15
3    2025-01-02
4    2025-03-02
5    2025-05-02
6    2025-10-02
7           NaT
8    2025-01-03
9    2025-05-03
10   2025-10-03
11   2025-12-03
12   2025-03-15
13          NaT
14   2025-01-04
15   2025-05-04
16   2025-05-04
17   2025-05-04
18   2025-10-04
19   2025-04-15
Name: Last_Update, dtype: datetime64[us]

In [278]:
#Analysising the data
restocking = df[df["Quantity"] < df["Reorder_Level"]]

restocking

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
4,P005,Mouse,Accessories,Compu Store,-5.0,20.0,10,2025-03-02
18,P018,Desk,Office Supplies,OfficeHub,-10.0,120.0,5,2025-10-04

In [273]:
average_price =df.groupby("Category")["Unit_Price"].mean().round(2).sort_values(ascending=False)
average_price

Category
Electronics        91375.82
Office Supplies      205.00
Accessories           22.00
Name: Unit_Price, dtype: float64

In [274]:
supplier = df["Supplier"].value_counts()
supplier

Supplier
TechWorld      9
CompuStore     4
Tech World     2
OfficeHub      2
Office Hub     2
Compu Store    1
Name: count, dtype: int64

In [275]:
df.sort_values(["Unit_Price"], ascending=False).head()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
12,P013,Tablet,Electronics,TechWorld,5.0,999999.0,3,2025-03-15
7,P008,Monitor,Electronics,TechWorld,10.0,1500.0,5,NaT
1,P002,Laptop,Electronics,Tech World,20.0,900.0,10,2025-12-01
0,P001,Laptop,Electronics,TechWorld,25.0,850.0,10,2025-10-01
2,P003,Laptop,Electronics,TechWorld,21.0,850.0,10,2025-01-15

In [276]:
df.sort_values(["Category","Unit_Price"], ascending=[True, False])

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
5,P006,Keyboard,Accessories,CompuStore,35.0,45.0,10,2025-05-02
3,P004,Mouse,Accessories,CompuStore,50.0,25.0,15,2025-01-02
4,P005,Mouse,Accessories,Compu Store,-5.0,20.0,10,2025-03-02
10,P011,Usb Cable,Accessories,CompuStore,100.0,10.0,20,2025-10-03
11,P012,Usb Cable,Accessories,CompuStore,NaN,10.0,20,2025-12-03
12,P013,Tablet,Electronics,TechWorld,5.0,999999.0,3,2025-03-15
7,P008,Monitor,Electronics,TechWorld,10.0,1500.0,5,NaT
1,P002,Laptop,Electronics,Tech World,20.0,900.0,10,2025-12-01
0,P001,Laptop,Electronics,TechWorld,25.0,850.0,10,2025-10-01
2,P003,Laptop,Electronics,TechWorld,21.0,850.0,10,2025-01-15
6,P007,,Electronics,TechWorld,15.0,700.0,5,2025-10-02
14,P015,Headphones,Electronics,Tech World,25.0,80.0,10,2025-01-04
13,P014,Headphones,Electronics,TechWorld,30.0,75.0,10,NaT
15,P016,Webcam,Electronics,TechWorld,17.0,60.0,5,2025-05-04
16,P017,Webcam,Electronics,TechWorld,18.0,60.0,5,2025-05-04
17,P017,Webcam,Electronics,TechWorld,18.0,60.0,5,2025-05-04
8,P009,Printer,Office Supplies,OfficeHub,8.0,300.0,3,2025-01-03
9,P010,Printer,Office Supplies,Office Hub,12.0,250.0,5,2025-05-03
19,P019,Chair,Office Supplies,Office Hub,30.0,150.0,10,2025-04-15
18,P018,Desk,Office Supplies,OfficeHub,-10.0,120.0,5,2025-10-04

In [277]:
df.drop_duplicates()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechWorld,25.0,850.0,10,2025-10-01
1,P002,Laptop,Electronics,Tech World,20.0,900.0,10,2025-12-01
2,P003,Laptop,Electronics,TechWorld,21.0,850.0,10,2025-01-15
3,P004,Mouse,Accessories,CompuStore,50.0,25.0,15,2025-01-02
4,P005,Mouse,Accessories,Compu Store,-5.0,20.0,10,2025-03-02
5,P006,Keyboard,Accessories,CompuStore,35.0,45.0,10,2025-05-02
6,P007,,Electronics,TechWorld,15.0,700.0,5,2025-10-02
7,P008,Monitor,Electronics,TechWorld,10.0,1500.0,5,NaT
8,P009,Printer,Office Supplies,OfficeHub,8.0,300.0,3,2025-01-03
9,P010,Printer,Office Supplies,Office Hub,12.0,250.0,5,2025-05-03
10,P011,Usb Cable,Accessories,CompuStore,100.0,10.0,20,2025-10-03
11,P012,Usb Cable,Accessories,CompuStore,NaN,10.0,20,2025-12-03
12,P013,Tablet,Electronics,TechWorld,5.0,999999.0,3,2025-03-15
13,P014,Headphones,Electronics,TechWorld,30.0,75.0,10,NaT
14,P015,Headphones,Electronics,Tech World,25.0,80.0,10,2025-01-04
15,P016,Webcam,Electronics,TechWorld,17.0,60.0,5,2025-05-04
16,P017,Webcam,Electronics,TechWorld,18.0,60.0,5,2025-05-04
18,P018,Desk,Office Supplies,OfficeHub,-10.0,120.0,5,2025-10-04
19,P019,Chair,Office Supplies,Office Hub,30.0,150.0,10,2025-04-15

#Summary