**Creating and Checking Dataset Info**

In [2]:
import pandas as pd
import numpy as np

In [3]:
store_data = {
    "Product_ID": [
        "P001", "P002", "P003", "P004", "P005", "P006", "P007", "P008", "P009", "P010",
        "P011", "P012", "P013", "P014", "P015", "P016", "P017", "P018", "P005", "P020"
    ],
    "Product_Name": [
        "Laptop", "ballpoint pen", "COFFEE MUG", "Notebook", "Kitchen Knife", "desk LAMP", "Headphones", "Water Bottle", 
        "STAPLER", "Tablet", "Paper Clips", "Electric Kettle", "External Hard Drive", "Cooking Spoon", "mouse", 
        "Bluetooth Speaker", None, "Lunch Box", "Notebook", "Smart Watch"
    ],
    "Category": [
        "Electronics", "stationery", "Kitchenware", "Stationery", "KITCHENWARE", "Home & Office", "electronics", 
        "Kitchenware", "STATIONERY", "electronics", "Office Supplies", "Kitchenware", "Storage", "kitchenware", 
        "OFFICE SUPPLIES", "Audio", "Cleaning Supplies", "HOME & KITCHEN", "stationery", "Wearables"
    ],
    "Supplier": [
        "TechWorld", "PaperPlus", "HomeGoods Ltd", "paperplus", "KitchenKing", "BrightHome", "AudioMax", "Home Goods Ltd", 
        "OfficeMart", "TECHWORLD", "OfficeMart", "Kitchen King", "StoragePlus", "Kitchen King", "OfficeMart", "AudioMax",
        "", "HomeGoods Ltd", "PaperPlus", "WearTech"
    ],
    "Quantity": [
        25, "twenty", 50, -5, 100, None, 15, 50, 30, 12, "ten", 45, -10, 75, 20, 8, 60, None, 20, 3
    ],
    "Unit_Price": [
        899.99, 25.50, 15.99, 45.00, None, 199.99, -20.00, 150.0, 9.99, 299.99, "49.99",
        120.00, 85.50, 30.00, 12.99, 75.00, 999.99, -5.00, 45.00, 250.75
    ],
    "Reorder_Level": [
        10, 15, 20, 5, 25, 10, 5, 50, 15, 10, 8, 20, 10, 15, 5, 10, 20, 5, 5, 10
    ],
    "Last_Update": [
        "2025-01-10", "2025/01/15", "10-02-2025", "2025-03-01", "", "March 15, 2025", "2025-04-10", "2025/04/25", 
        "05-05-2025", None, "2025-06-01", "June 15 2025", "2025/07/10", "2025-13-01", "2025-08-05", "08/20/2025", 
        "2025-09-01", "28/07/2025", "2025-03-01", ""
    ]
}

In [4]:
df = pd.DataFrame(store_data)

df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechWorld,25,899.99,10,2025-01-10
1,P002,ballpoint pen,stationery,PaperPlus,twenty,25.5,15,2025/01/15
2,P003,COFFEE MUG,Kitchenware,HomeGoods Ltd,50,15.99,20,10-02-2025
3,P004,Notebook,Stationery,paperplus,-5,45.0,5,2025-03-01
4,P005,Kitchen Knife,KITCHENWARE,KitchenKing,100,None,25,
5,P006,desk LAMP,Home & Office,BrightHome,None,199.99,10,"March 15, 2025"
6,P007,Headphones,electronics,AudioMax,15,-20.0,5,2025-04-10
7,P008,Water Bottle,Kitchenware,Home Goods Ltd,50,150.0,50,2025/04/25
8,P009,STAPLER,STATIONERY,OfficeMart,30,9.99,15,05-05-2025
9,P010,Tablet,electronics,TECHWORLD,12,299.99,10,NaN
10,P011,Paper Clips,Office Supplies,OfficeMart,ten,49.99,8,2025-06-01
11,P012,Electric Kettle,Kitchenware,Kitchen King,45,120.0,20,June 15 2025
12,P013,External Hard Drive,Storage,StoragePlus,-10,85.5,10,2025/07/10
13,P014,Cooking Spoon,kitchenware,Kitchen King,75,30.0,15,2025-13-01
14,P015,mouse,OFFICE SUPPLIES,OfficeMart,20,12.99,5,2025-08-05
15,P016,Bluetooth Speaker,Audio,AudioMax,8,75.0,10,08/20/2025
16,P017,NaN,Cleaning Supplies,,60,999.99,20,2025-09-01
17,P018,Lunch Box,HOME & KITCHEN,HomeGoods Ltd,None,-5.0,5,28/07/2025
18,P005,Notebook,stationery,PaperPlus,20,45.0,5,2025-03-01
19,P020,Smart Watch,Wearables,WearTech,3,250.75,10,

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     20 non-null     str
 1   Product_Name   19 non-null     str
 2   Category       20 non-null     str
 3   Supplier       20 non-null     str
 4   Quantity       18 non-null     object
 5   Unit_Price     19 non-null     object
 6   Reorder_Level  20 non-null     int64
 7   Last_Update    19 non-null     str
dtypes: int64(1), object(2), str(5)
memory usage: 1.4+ KB

In [6]:
df.describe()

       Reorder_Level
count      20.000000
mean       13.650000
std        10.418986
min         5.000000
25%         7.250000
50%        10.000000
75%        16.250000
max        50.000000

In [7]:
df.describe(include="all")

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
count,20,19,20,20,18.0,19.0,20.000000,19
unique,19,18,16,14,16.0,18.0,NaN,17
top,P005,Notebook,Kitchenware,OfficeMart,50.0,45.0,NaN,2025-03-01
freq,2,2,3,3,2.0,2.0,NaN,2
mean,NaN,NaN,NaN,NaN,NaN,NaN,13.650000,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,10.418986,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,7.250000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,16.250000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,50.000000,NaN

In [8]:
df.isnull().sum()

Product_ID       0
Product_Name     1
Category         0
Supplier         0
Quantity         2
Unit_Price       1
Reorder_Level    0
Last_Update      1
dtype: int64

In [9]:
df[df.duplicated()]

Empty DataFrame
Columns: [Product_ID, Product_Name, Category, Supplier, Quantity, Unit_Price, Reorder_Level, Last_Update]
Index: []

**Cleaning Dataset**

In [10]:
pd.set_option('display.max_rows', None)
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechWorld,25,899.99,10,2025-01-10
1,P002,ballpoint pen,stationery,PaperPlus,twenty,25.5,15,2025/01/15
2,P003,COFFEE MUG,Kitchenware,HomeGoods Ltd,50,15.99,20,10-02-2025
3,P004,Notebook,Stationery,paperplus,-5,45.0,5,2025-03-01
4,P005,Kitchen Knife,KITCHENWARE,KitchenKing,100,None,25,
5,P006,desk LAMP,Home & Office,BrightHome,None,199.99,10,"March 15, 2025"
6,P007,Headphones,electronics,AudioMax,15,-20.0,5,2025-04-10
7,P008,Water Bottle,Kitchenware,Home Goods Ltd,50,150.0,50,2025/04/25
8,P009,STAPLER,STATIONERY,OfficeMart,30,9.99,15,05-05-2025
9,P010,Tablet,electronics,TECHWORLD,12,299.99,10,NaN
10,P011,Paper Clips,Office Supplies,OfficeMart,ten,49.99,8,2025-06-01
11,P012,Electric Kettle,Kitchenware,Kitchen King,45,120.0,20,June 15 2025
12,P013,External Hard Drive,Storage,StoragePlus,-10,85.5,10,2025/07/10
13,P014,Cooking Spoon,kitchenware,Kitchen King,75,30.0,15,2025-13-01
14,P015,mouse,OFFICE SUPPLIES,OfficeMart,20,12.99,5,2025-08-05
15,P016,Bluetooth Speaker,Audio,AudioMax,8,75.0,10,08/20/2025
16,P017,NaN,Cleaning Supplies,,60,999.99,20,2025-09-01
17,P018,Lunch Box,HOME & KITCHEN,HomeGoods Ltd,None,-5.0,5,28/07/2025
18,P005,Notebook,stationery,PaperPlus,20,45.0,5,2025-03-01
19,P020,Smart Watch,Wearables,WearTech,3,250.75,10,

In [11]:
df[df["Product_ID"] == "P005"]

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
4,P005,Kitchen Knife,KITCHENWARE,KitchenKing,100,None,25,
18,P005,Notebook,stationery,PaperPlus,20,45.0,5,2025-03-01

In [12]:
df.loc[18, "Product_ID"] = "P019"

In [13]:
df.tail()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
15,P016,Bluetooth Speaker,Audio,AudioMax,8,75.0,10,08/20/2025
16,P017,NaN,Cleaning Supplies,,60,999.99,20,2025-09-01
17,P018,Lunch Box,HOME & KITCHEN,HomeGoods Ltd,None,-5.0,5,28/07/2025
18,P019,Notebook,stationery,PaperPlus,20,45.0,5,2025-03-01
19,P020,Smart Watch,Wearables,WearTech,3,250.75,10,

In [14]:
df["Product_Name"] = (
    df["Product_Name"]
    .str.strip()
    .str.title()
    .tolist()
)
df["Product_Name"]

0                  Laptop
1           Ballpoint Pen
2              Coffee Mug
3                Notebook
4           Kitchen Knife
5               Desk Lamp
6              Headphones
7            Water Bottle
8                 Stapler
9                  Tablet
10            Paper Clips
11        Electric Kettle
12    External Hard Drive
13          Cooking Spoon
14                  Mouse
15      Bluetooth Speaker
16                    NaN
17              Lunch Box
18               Notebook
19            Smart Watch
Name: Product_Name, dtype: str

In [15]:
df["Category"] = (
    df["Category"]
    .str.strip()
    .str.title()
    .tolist()
)
df["Category"]

0           Electronics
1            Stationery
2           Kitchenware
3            Stationery
4           Kitchenware
5         Home & Office
6           Electronics
7           Kitchenware
8            Stationery
9           Electronics
10      Office Supplies
11          Kitchenware
12              Storage
13          Kitchenware
14      Office Supplies
15                Audio
16    Cleaning Supplies
17       Home & Kitchen
18           Stationery
19            Wearables
Name: Category, dtype: str

In [16]:
df["Supplier"] = (
    df["Supplier"]
    .str.strip()
    .str.title()
    .tolist()
)
df["Supplier"]

0          Techworld
1          Paperplus
2      Homegoods Ltd
3          Paperplus
4        Kitchenking
5         Brighthome
6           Audiomax
7     Home Goods Ltd
8         Officemart
9          Techworld
10        Officemart
11      Kitchen King
12       Storageplus
13      Kitchen King
14        Officemart
15          Audiomax
16
17     Homegoods Ltd
18         Paperplus
19          Weartech
Name: Supplier, dtype: str

In [17]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techworld,25,899.99,10,2025-01-10
1,P002,Ballpoint Pen,Stationery,Paperplus,twenty,25.5,15,2025/01/15
2,P003,Coffee Mug,Kitchenware,Homegoods Ltd,50,15.99,20,10-02-2025
3,P004,Notebook,Stationery,Paperplus,-5,45.0,5,2025-03-01
4,P005,Kitchen Knife,Kitchenware,Kitchenking,100,None,25,
5,P006,Desk Lamp,Home & Office,Brighthome,None,199.99,10,"March 15, 2025"
6,P007,Headphones,Electronics,Audiomax,15,-20.0,5,2025-04-10
7,P008,Water Bottle,Kitchenware,Home Goods Ltd,50,150.0,50,2025/04/25
8,P009,Stapler,Stationery,Officemart,30,9.99,15,05-05-2025
9,P010,Tablet,Electronics,Techworld,12,299.99,10,NaN
10,P011,Paper Clips,Office Supplies,Officemart,ten,49.99,8,2025-06-01
11,P012,Electric Kettle,Kitchenware,Kitchen King,45,120.0,20,June 15 2025
12,P013,External Hard Drive,Storage,Storageplus,-10,85.5,10,2025/07/10
13,P014,Cooking Spoon,Kitchenware,Kitchen King,75,30.0,15,2025-13-01
14,P015,Mouse,Office Supplies,Officemart,20,12.99,5,2025-08-05
15,P016,Bluetooth Speaker,Audio,Audiomax,8,75.0,10,08/20/2025
16,P017,NaN,Cleaning Supplies,,60,999.99,20,2025-09-01
17,P018,Lunch Box,Home & Kitchen,Homegoods Ltd,None,-5.0,5,28/07/2025
18,P019,Notebook,Stationery,Paperplus,20,45.0,5,2025-03-01
19,P020,Smart Watch,Wearables,Weartech,3,250.75,10,

In [18]:
df["Quantity"].to_list()

[25,
 'twenty',
 50,
 -5,
 100,
 None,
 15,
 50,
 30,
 12,
 'ten',
 45,
 -10,
 75,
 20,
 8,
 60,
 None,
 20,
 3]

In [19]:
def clean_quantity(value):
    if value == "twenty":
        return 20
    elif value == "ten":
        return 10
    elif isinstance(value, (int, float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else: 
        return np.nan

df["Quantity"] = df["Quantity"].apply(clean_quantity)
df["Quantity"] = df["Quantity"].abs()
df["Quantity"]

0      25.0
1      20.0
2      50.0
3       5.0
4     100.0
5       NaN
6      15.0
7      50.0
8      30.0
9      12.0
10     10.0
11     45.0
12     10.0
13     75.0
14     20.0
15      8.0
16     60.0
17      NaN
18     20.0
19      3.0
Name: Quantity, dtype: float64

In [20]:
df["Unit_Price"].to_list()

[899.99,
 25.5,
 15.99,
 45.0,
 None,
 199.99,
 -20.0,
 150.0,
 9.99,
 299.99,
 '49.99',
 120.0,
 85.5,
 30.0,
 12.99,
 75.0,
 999.99,
 -5.0,
 45.0,
 250.75]

In [21]:
df["Unit_Price"] = (
    df["Unit_Price"]
    .astype(str)
    .replace("Nan", np.nan)
    .astype(float)
)
df["Unit_Price"]

0     899.99
1      25.50
2      15.99
3      45.00
4        NaN
5     199.99
6     -20.00
7     150.00
8       9.99
9     299.99
10     49.99
11    120.00
12     85.50
13     30.00
14     12.99
15     75.00
16    999.99
17     -5.00
18     45.00
19    250.75
Name: Unit_Price, dtype: float64

In [22]:
#removing rows with unit price less than 0
df = df[df["Unit_Price"] >= 0]

In [23]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techworld,25.0,899.99,10,2025-01-10
1,P002,Ballpoint Pen,Stationery,Paperplus,20.0,25.50,15,2025/01/15
2,P003,Coffee Mug,Kitchenware,Homegoods Ltd,50.0,15.99,20,10-02-2025
3,P004,Notebook,Stationery,Paperplus,5.0,45.00,5,2025-03-01
5,P006,Desk Lamp,Home & Office,Brighthome,NaN,199.99,10,"March 15, 2025"
7,P008,Water Bottle,Kitchenware,Home Goods Ltd,50.0,150.00,50,2025/04/25
8,P009,Stapler,Stationery,Officemart,30.0,9.99,15,05-05-2025
9,P010,Tablet,Electronics,Techworld,12.0,299.99,10,NaN
10,P011,Paper Clips,Office Supplies,Officemart,10.0,49.99,8,2025-06-01
11,P012,Electric Kettle,Kitchenware,Kitchen King,45.0,120.00,20,June 15 2025
12,P013,External Hard Drive,Storage,Storageplus,10.0,85.50,10,2025/07/10
13,P014,Cooking Spoon,Kitchenware,Kitchen King,75.0,30.00,15,2025-13-01
14,P015,Mouse,Office Supplies,Officemart,20.0,12.99,5,2025-08-05
15,P016,Bluetooth Speaker,Audio,Audiomax,8.0,75.00,10,08/20/2025
16,P017,NaN,Cleaning Supplies,,60.0,999.99,20,2025-09-01
18,P019,Notebook,Stationery,Paperplus,20.0,45.00,5,2025-03-01
19,P020,Smart Watch,Wearables,Weartech,3.0,250.75,10,

In [24]:
from dateutil import parser

def clean_date(date_str):
    try:
        return parser.parse(date_str, dayfirst=True)
    except Exception:
        return pd.NaT

df["Last_Update"] = df["Last_Update"].apply(clean_date)
df["Last_Update"]

0    2025-10-01
1    2025-01-15
2    2025-02-10
3    2025-01-03
5    2025-03-15
7    2025-04-25
8    2025-05-05
9           NaT
10   2025-01-06
11   2025-06-15
12   2025-10-07
13   2025-01-13
14   2025-05-08
15   2025-08-20
16   2025-01-09
18   2025-01-03
19          NaT
Name: Last_Update, dtype: datetime64[us]

In [25]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techworld,25.0,899.99,10,2025-10-01
1,P002,Ballpoint Pen,Stationery,Paperplus,20.0,25.50,15,2025-01-15
2,P003,Coffee Mug,Kitchenware,Homegoods Ltd,50.0,15.99,20,2025-02-10
3,P004,Notebook,Stationery,Paperplus,5.0,45.00,5,2025-01-03
5,P006,Desk Lamp,Home & Office,Brighthome,NaN,199.99,10,2025-03-15
7,P008,Water Bottle,Kitchenware,Home Goods Ltd,50.0,150.00,50,2025-04-25
8,P009,Stapler,Stationery,Officemart,30.0,9.99,15,2025-05-05
9,P010,Tablet,Electronics,Techworld,12.0,299.99,10,NaT
10,P011,Paper Clips,Office Supplies,Officemart,10.0,49.99,8,2025-01-06
11,P012,Electric Kettle,Kitchenware,Kitchen King,45.0,120.00,20,2025-06-15
12,P013,External Hard Drive,Storage,Storageplus,10.0,85.50,10,2025-10-07
13,P014,Cooking Spoon,Kitchenware,Kitchen King,75.0,30.00,15,2025-01-13
14,P015,Mouse,Office Supplies,Officemart,20.0,12.99,5,2025-05-08
15,P016,Bluetooth Speaker,Audio,Audiomax,8.0,75.00,10,2025-08-20
16,P017,NaN,Cleaning Supplies,,60.0,999.99,20,2025-01-09
18,P019,Notebook,Stationery,Paperplus,20.0,45.00,5,2025-01-03
19,P020,Smart Watch,Wearables,Weartech,3.0,250.75,10,NaT

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 17 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     17 non-null     str
 1   Product_Name   16 non-null     str
 2   Category       17 non-null     str
 3   Supplier       17 non-null     str
 4   Quantity       16 non-null     float64
 5   Unit_Price     17 non-null     float64
 6   Reorder_Level  17 non-null     int64
 7   Last_Update    15 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 1.2 KB

In [27]:
df["Product_Name"] = df["Product_Name"].fillna("Unknown")

df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mode()[0])

df["Last_Update"] = df["Last_Update"].fillna(df["Last_Update"].mode()[0])

In [28]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techworld,25.0,899.99,10,2025-10-01
1,P002,Ballpoint Pen,Stationery,Paperplus,20.0,25.50,15,2025-01-15
2,P003,Coffee Mug,Kitchenware,Homegoods Ltd,50.0,15.99,20,2025-02-10
3,P004,Notebook,Stationery,Paperplus,5.0,45.00,5,2025-01-03
5,P006,Desk Lamp,Home & Office,Brighthome,20.0,199.99,10,2025-03-15
7,P008,Water Bottle,Kitchenware,Home Goods Ltd,50.0,150.00,50,2025-04-25
8,P009,Stapler,Stationery,Officemart,30.0,9.99,15,2025-05-05
9,P010,Tablet,Electronics,Techworld,12.0,299.99,10,2025-01-03
10,P011,Paper Clips,Office Supplies,Officemart,10.0,49.99,8,2025-01-06
11,P012,Electric Kettle,Kitchenware,Kitchen King,45.0,120.00,20,2025-06-15
12,P013,External Hard Drive,Storage,Storageplus,10.0,85.50,10,2025-10-07
13,P014,Cooking Spoon,Kitchenware,Kitchen King,75.0,30.00,15,2025-01-13
14,P015,Mouse,Office Supplies,Officemart,20.0,12.99,5,2025-05-08
15,P016,Bluetooth Speaker,Audio,Audiomax,8.0,75.00,10,2025-08-20
16,P017,Unknown,Cleaning Supplies,,60.0,999.99,20,2025-01-09
18,P019,Notebook,Stationery,Paperplus,20.0,45.00,5,2025-01-03
19,P020,Smart Watch,Wearables,Weartech,3.0,250.75,10,2025-01-03

In [36]:
df.describe()

        Quantity  Unit_Price  Reorder_Level                 Last_Update
count  17.000000   17.000000      17.000000                          17
mean   27.235294  195.039412      14.000000  2025-03-28 15:31:45.882353
min     3.000000    9.990000       5.000000         2025-01-03 00:00:00
25%    10.000000   30.000000      10.000000         2025-01-06 00:00:00
50%    20.000000   75.000000      10.000000         2025-02-10 00:00:00
75%    45.000000  199.990000      15.000000         2025-05-08 00:00:00
max    75.000000  999.990000      50.000000         2025-10-07 00:00:00
std    21.223600  297.342391      10.553435                         NaN

In [29]:
df["Supplier"] = df["Supplier"].replace("", "Unknown")

In [30]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techworld,25.0,899.99,10,2025-10-01
1,P002,Ballpoint Pen,Stationery,Paperplus,20.0,25.50,15,2025-01-15
2,P003,Coffee Mug,Kitchenware,Homegoods Ltd,50.0,15.99,20,2025-02-10
3,P004,Notebook,Stationery,Paperplus,5.0,45.00,5,2025-01-03
5,P006,Desk Lamp,Home & Office,Brighthome,20.0,199.99,10,2025-03-15
7,P008,Water Bottle,Kitchenware,Home Goods Ltd,50.0,150.00,50,2025-04-25
8,P009,Stapler,Stationery,Officemart,30.0,9.99,15,2025-05-05
9,P010,Tablet,Electronics,Techworld,12.0,299.99,10,2025-01-03
10,P011,Paper Clips,Office Supplies,Officemart,10.0,49.99,8,2025-01-06
11,P012,Electric Kettle,Kitchenware,Kitchen King,45.0,120.00,20,2025-06-15
12,P013,External Hard Drive,Storage,Storageplus,10.0,85.50,10,2025-10-07
13,P014,Cooking Spoon,Kitchenware,Kitchen King,75.0,30.00,15,2025-01-13
14,P015,Mouse,Office Supplies,Officemart,20.0,12.99,5,2025-05-08
15,P016,Bluetooth Speaker,Audio,Audiomax,8.0,75.00,10,2025-08-20
16,P017,Unknown,Cleaning Supplies,Unknown,60.0,999.99,20,2025-01-09
18,P019,Notebook,Stationery,Paperplus,20.0,45.00,5,2025-01-03
19,P020,Smart Watch,Wearables,Weartech,3.0,250.75,10,2025-01-03

**PART 4: ANALYSIS AND SORTING**

In [31]:
#1 Which products need restocking (where Quantity < Reorder_Level)?
df[df["Quantity"] < df["Reorder_Level"]]

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
15,P016,Bluetooth Speaker,Audio,Audiomax,8.0,75.00,10,2025-08-20
19,P020,Smart Watch,Wearables,Weartech,3.0,250.75,10,2025-01-03

In [32]:
#What is the average unit price per category?
df["Unit_Price"] = pd.to_numeric(df["Unit_Price"], errors="coerce")

df.groupby("Category")["Unit_Price"].mean()

Category
Audio                 75.0000
Cleaning Supplies    999.9900
Electronics          599.9900
Home & Office        199.9900
Kitchenware           78.9975
Office Supplies       31.4900
Stationery            31.3725
Storage               85.5000
Wearables            250.7500
Name: Unit_Price, dtype: float64

In [33]:
#Which supplier provides the most products?
df["Supplier"].value_counts()

Supplier
Paperplus         3
Officemart        3
Techworld         2
Kitchen King      2
Homegoods Ltd     1
Brighthome        1
Home Goods Ltd    1
Storageplus       1
Audiomax          1
Unknown           1
Weartech          1
Name: count, dtype: int64

In [34]:
#List the top 5 most expensive products.
df.sort_values(["Unit_Price"], ascending=False).head()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
16,P017,Unknown,Cleaning Supplies,Unknown,60.0,999.99,20,2025-01-09
0,P001,Laptop,Electronics,Techworld,25.0,899.99,10,2025-10-01
9,P010,Tablet,Electronics,Techworld,12.0,299.99,10,2025-01-03
19,P020,Smart Watch,Wearables,Weartech,3.0,250.75,10,2025-01-03
5,P006,Desk Lamp,Home & Office,Brighthome,20.0,199.99,10,2025-03-15

In [35]:
#Sort the cleaned dataset by Category and then by Unit_Price in descending order.
df.sort_values(["Category", "Unit_Price"], ascending=[True,False])

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
15,P016,Bluetooth Speaker,Audio,Audiomax,8.0,75.00,10,2025-08-20
16,P017,Unknown,Cleaning Supplies,Unknown,60.0,999.99,20,2025-01-09
0,P001,Laptop,Electronics,Techworld,25.0,899.99,10,2025-10-01
9,P010,Tablet,Electronics,Techworld,12.0,299.99,10,2025-01-03
5,P006,Desk Lamp,Home & Office,Brighthome,20.0,199.99,10,2025-03-15
7,P008,Water Bottle,Kitchenware,Home Goods Ltd,50.0,150.00,50,2025-04-25
11,P012,Electric Kettle,Kitchenware,Kitchen King,45.0,120.00,20,2025-06-15
13,P014,Cooking Spoon,Kitchenware,Kitchen King,75.0,30.00,15,2025-01-13
2,P003,Coffee Mug,Kitchenware,Homegoods Ltd,50.0,15.99,20,2025-02-10
10,P011,Paper Clips,Office Supplies,Officemart,10.0,49.99,8,2025-01-06
14,P015,Mouse,Office Supplies,Officemart,20.0,12.99,5,2025-05-08
3,P004,Notebook,Stationery,Paperplus,5.0,45.00,5,2025-01-03
18,P019,Notebook,Stationery,Paperplus,20.0,45.00,5,2025-01-03
1,P002,Ballpoint Pen,Stationery,Paperplus,20.0,25.50,15,2025-01-15
8,P009,Stapler,Stationery,Officemart,30.0,9.99,15,2025-05-05
12,P013,External Hard Drive,Storage,Storageplus,10.0,85.50,10,2025-10-07
19,P020,Smart Watch,Wearables,Weartech,3.0,250.75,10,2025-01-03

**SUMMARY**

The retial analysis dataset consist of 20 records of variety of product which was later reduced to 17 records after cleaning. The average quantity is **20**, while the average unit price and average reoder level are **75** and **10**, respectively. Also, the analysis shows that the top suppliers are **Paperplus** and **Officemart**. However, the most expensive product in the record is **unknown**, which is followed by **Laptop** and **Tablet**, respectively. The analysis also identified the products that needs to be restocked as soon as possible which are **Bluetooth Speaker** and **Smart watch**.