In [1]:
#import libraries
import pandas as pd
import numpy as np

In [2]:
#create messey sample dataset
data = {
    "EmpId": [101, 102, "103", 104, 105, 106, 107, 108, 109, 110],
    "fullName": [
        "  Alice Johnson  ", "MICHEAL smith", "sarah lee", "David-Kim", None, "john brown",
        "Emma Wilson", "TOM  davis", "Jane Miller", "Chris taylor"
    ], 
     "Dept": ["IT", "hr", "Mktng", "IT", "Customer Care", "marketing", "Finance", None, "HR", "marketing"],
    "Age": [29, "thirty-five", 26, 31, 42, 27, 33, 30, None, 28],
    "Salary($)": ["$5500.50", "4800", "4200.75", "NaN", "6100", "4,300", "5800", "5000", "4700.0", "4400"],
    "JoinDate" : [ 
        "12-04-2021" , "2020.11.01" , "Jan 18, 2022" , "2019/9/25" , "07/05/18" , "2021-10-14" , 
        "2019/12/01" , "2020-03-22" , "May 10th, 2021" , "2022-02-05" 
    ],
    "Performance": [87, "73", 90, 65, 82, 75, 88, None, "79%", "91"],
    "Remote?": ["Yes", "No", "Y", "N", "yes", "no", "Y", "Yes", None, "True"]
}

In [3]:
#create a dataframe for the data
df = pd.DataFrame(data)

#covert the dataframe to csv file
df1 = df.to_csv("employee_data.csv", index=False)

#load dataset
df = pd.read_csv("employee_data.csv")
df.head()

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes

In [4]:
#get shape of the dataset
df.shape

(10, 8)

In [5]:
#get the information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpId        10 non-null     int64
 1   fullName     9 non-null      object
 2   Dept         9 non-null      object
 3   Age          9 non-null      object
 4   Salary($)    9 non-null      object
 5   JoinDate     10 non-null     object
 6   Performance  9 non-null      object
 7   Remote?      9 non-null      object
dtypes: int64(1), object(7)
memory usage: 768.0+ bytes

In [6]:
#get columns from dataset
df.columns

Index(['EmpId', 'fullName', 'Dept', 'Age', 'Salary($)', 'JoinDate',
       'Performance', 'Remote?'],
      dtype='object')

In [7]:
#get missing value count
df.isnull().sum()

EmpId          0
fullName       1
Dept           1
Age            1
Salary($)      1
JoinDate       0
Performance    1
Remote?        1
dtype: int64

In [8]:
#get unique values columns
print(df["Dept"].unique())
print(df["Age"].unique())
print(df["Remote?"].unique())

['IT' 'hr' 'Mktng' 'Customer Care' 'marketing' 'Finance' nan 'HR']
['29' 'thirty-five' '26' '31' '42' '27' '33' '30' nan '28']
['Yes' 'No' 'Y' 'N' 'yes' 'no' nan 'True']

In [9]:
#access series data
df["Salary($)"].to_list()

['$5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [10]:
df["fullName"].to_list()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [11]:
df["Salary($)"].head()

0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
Name: Salary($), dtype: object

In [12]:
#start cleaning inconsistent values
#rename inconsistent columns
df.rename(columns={
    "EmpId": "Employee Id",
    "fullName": "Full Name",
    "Dept": "Department",
    "Salary($)": "Salary",
    "JoinDate": "Join Date",
    "Remote?": "Remote"
}, inplace=True)

df

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [13]:
#clean inconsistent value on full name
df["Full Name"] = (
    df["Full Name"]
    .str.strip()
    .str.title()
    .str.replace(r"[\s-]+", " ", regex=True)
    .tolist()
)

df["Full Name"]

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4              NaN
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: Full Name, dtype: object

In [14]:
#clean inconsistent value in department
df.replace({
    "hr": "HR",
    "Mktng": "Marketing",
    "marketing": "Marketing"
}, inplace=True)

df["Department"].to_list()

['IT',
 'HR',
 'Marketing',
 'IT',
 'Customer Care',
 'Marketing',
 'Finance',
 nan,
 'HR',
 'Marketing']

In [15]:
#clean inconsistent value in age
def clean_age(value):
    if value == "thirty-five":
        return 35
    elif isinstance(value, (int, float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else:
        return np.nan

df["Age"] = df["Age"].apply(clean_age)

df["Age"]

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8     NaN
9    28.0
Name: Age, dtype: float64

In [16]:
#clean inconsistent value in salary column
df["Salary"] = (
    df["Salary"]
    .astype(str)
    .replace('[$,]', "", regex=True)
    .replace("NaN", np.nan)
    .astype(float)
)

df["Salary"]

0    5500.50
1    4800.00
2    4200.75
3        NaN
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: Salary, dtype: float64

In [17]:
from dateutil import parser

def clean_date(date_str):
    try:
        return parser.parse(date_str, dayfirst=True)
    except Exception:
        return pd.NaT

df["Join Date"] = df["Join Date"].apply(clean_date)
df["Join Date"]

0   2021-04-12
1   2020-01-11
2   2022-01-18
3   2019-09-25
4   2018-05-07
5   2021-10-14
6   2019-01-12
7   2020-03-22
8   2021-05-10
9   2022-05-02
Name: Join Date, dtype: datetime64[ns]

In [18]:
df["Performance"] = (
    df["Performance"]
    .astype(str)
    .replace("%", "", regex=True)
    .replace("None", np.nan)
    .astype(float)
)

df["Performance"]

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7     NaN
8    79.0
9    91.0
Name: Performance, dtype: float64

In [19]:
df.replace({
    "Y": "Yes",
    "N": "No",
    "yes": "Yes",
    "no": "No",
    "None": np.nan,
    "True": "Yes"
}, inplace=True)

df["Remote"]

0    Yes
1     No
2    Yes
3     No
4    Yes
5     No
6    Yes
7    Yes
8    NaN
9    Yes
Name: Remote, dtype: object

In [20]:
df["Employee Id"] = pd.to_numeric(df["Employee Id"], errors="coerce")
df["Employee Id"]

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: Employee Id, dtype: int64

In [21]:
#handling missing values
df["Full Name"] = df["Full Name"].fillna("Unknown")
df["Full Name"]

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: Full Name, dtype: object

In [22]:
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])
df["Department"]

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7        Marketing
8               HR
9        Marketing
Name: Department, dtype: object

In [23]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Age"]

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8    30.0
9    28.0
Name: Age, dtype: float64

In [24]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
df["Salary"]

0    5500.50
1    4800.00
2    4200.75
3    4800.00
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: Salary, dtype: float64

In [25]:
df["Performance"] = df["Performance"].fillna(df["Performance"].median())
df["Performance"]

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7    82.0
8    79.0
9    91.0
Name: Performance, dtype: float64

In [26]:
df["Remote"] = df["Remote"].fillna(df["Remote"].mode()[0])
df["Remote"]

0    Yes
1     No
2    Yes
3     No
4    Yes
5     No
6    Yes
7    Yes
8    Yes
9    Yes
Name: Remote, dtype: object

In [27]:
#working with filtering data
df.head()

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-01-11,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
4,105,Unknown,Customer Care,42.0,6100.00,2018-05-07,82.0,Yes

In [28]:
df["Full Name"]

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: Full Name, dtype: object

In [30]:
df[["Full Name", "Department", "Salary"]]

       Full Name     Department   Salary
0  Alice Johnson             IT  5500.50
1  Micheal Smith             HR  4800.00
2      Sarah Lee      Marketing  4200.75
3      David Kim             IT  4800.00
4        Unknown  Customer Care  6100.00
5     John Brown      Marketing  4300.00
6    Emma Wilson        Finance  5800.00
7      Tom Davis      Marketing  5000.00
8    Jane Miller             HR  4700.00
9   Chris Taylor      Marketing  4400.00

In [38]:
df.iloc[0:11, 0:3]

   Employee Id      Full Name     Department
0          101  Alice Johnson             IT
1          102  Micheal Smith             HR
2          103      Sarah Lee      Marketing
3          104      David Kim             IT
4          105        Unknown  Customer Care
5          106     John Brown      Marketing
6          107    Emma Wilson        Finance
7          108      Tom Davis      Marketing
8          109    Jane Miller             HR
9          110   Chris Taylor      Marketing

In [39]:
df.iloc[0:3]

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-01-11,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes

In [33]:
df.loc[df["Salary"] >= 5000]

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
4,105,Unknown,Customer Care,42.0,6100.0,2018-05-07,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.0,2019-01-12,88.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.0,2020-03-22,82.0,Yes

In [40]:
df.loc[df["Salary"] >= 5000, ["Full Name", "Department", "Salary"]]

       Full Name     Department  Salary
0  Alice Johnson             IT  5500.5
4        Unknown  Customer Care  6100.0
6    Emma Wilson        Finance  5800.0
7      Tom Davis      Marketing  5000.0

In [36]:
df.loc[:, "Salary"]

0    5500.50
1    4800.00
2    4200.75
3    4800.00
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: Salary, dtype: float64

In [41]:
df[df["Department"] == "IT"]

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
3,104,David Kim,IT,31.0,4800.0,2019-09-25,65.0,No

In [43]:
df[df["Age"] > 30]

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
1,102,Micheal Smith,HR,35.0,4800.0,2020-01-11,73.0,No
3,104,David Kim,IT,31.0,4800.0,2019-09-25,65.0,No
4,105,Unknown,Customer Care,42.0,6100.0,2018-05-07,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.0,2019-01-12,88.0,Yes

In [45]:
df[
    (df["Salary"] >= 5000) & (df["Department"] == "IT")
]

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes

In [47]:
df[
    (df["Salary"] >= 7000) | (df["Remote"] == "Yes")
]

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
4,105,Unknown,Customer Care,42.0,6100.00,2018-05-07,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.00,2019-01-12,88.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-05-02,91.0,Yes

In [50]:
df[df["Department"].str.startswith("M")]

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-05-02,91.0,Yes

In [53]:
df[df["Department"].isin(["IT", "HR"])]

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
1,102,Micheal Smith,HR,35.0,4800.0,2020-01-11,73.0,No
3,104,David Kim,IT,31.0,4800.0,2019-09-25,65.0,No
8,109,Jane Miller,HR,30.0,4700.0,2021-05-10,79.0,Yes

In [56]:
df[df["Full Name"].str.contains("john", case=False)]

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
5,106,John Brown,Marketing,27.0,4300.0,2021-10-14,75.0,No

In [58]:
#working with sort
df.sort_values("Salary", ascending=False)

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
4,105,Unknown,Customer Care,42.0,6100.00,2018-05-07,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.00,2019-01-12,88.0,Yes
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-01-11,73.0,No
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-05-02,91.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes

In [59]:
df.sort_values("Performance", ascending=False)

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-05-02,91.0,Yes
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.00,2019-01-12,88.0,Yes
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
4,105,Unknown,Customer Care,42.0,6100.00,2018-05-07,82.0,Yes
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
1,102,Micheal Smith,HR,35.0,4800.00,2020-01-11,73.0,No
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No

In [61]:
df.sort_values(["Department", "Salary"], ascending=[False, True])

,Employee Id,Full Name,Department,Age,Salary,Join Date,Performance,Remote
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-05-02,91.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-01-11,73.0,No
6,107,Emma Wilson,Finance,33.0,5800.00,2019-01-12,88.0,Yes
4,105,Unknown,Customer Care,42.0,6100.00,2018-05-07,82.0,Yes

In [63]:
df["Department"].value_counts()

Department
Marketing        4
IT               2
HR               2
Customer Care    1
Finance          1
Name: count, dtype: int64

In [64]:
df["Department"].value_counts(normalize=True)

Department
Marketing        0.4
IT               0.2
HR               0.2
Customer Care    0.1
Finance          0.1
Name: proportion, dtype: float64

In [67]:
df["Remote"].value_counts(normalize=True)

Remote
Yes    0.7
No     0.3
Name: proportion, dtype: float64